//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBokingMSSQLdatabase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bio_bookingEntities : DbContext
    {
        public bio_bookingEntities()
            : base("name=bio_bookingEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cinemas> cinemas { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<movies> movies { get; set; }
        public virtual DbSet<auditoriums> auditoriums { get; set; }
        public virtual DbSet<authentication> authentication { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<shows> shows { get; set; }
    }
}
