//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBokingMSSQLdatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservations()
        {
            this.payments = new HashSet<payments>();
        }
    
        public long id { get; set; }
        public long user_id { get; set; }
        public long show_id { get; set; }
        public int seat_count { get; set; }
        public int first_seat_number { get; set; }
        public System.DateTime reserved_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payments> payments { get; set; }
        public virtual shows show { get; set; }
        public virtual users user { get; set; }
    }
}
