//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBokingMSSQLdatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shows()
        {
            this.reservations = new HashSet<reservations>();
        }
    
        public long id { get; set; }
        public long movie_id { get; set; }
        public long auditorium_id { get; set; }
        public string spoken_language { get; set; }
        public Nullable<long> subtitle_language { get; set; }
        public short seat_price { get; set; }
        public System.DateTime start_at { get; set; }
    
        public virtual movies movie { get; set; }
        public virtual auditoriums auditorium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservations> reservations { get; set; }
    }
}
